### ISSUE TITLE
Can I run the cloudsql-proxy as a daemon set?

### ISSUE THREAD

**Issue by edwardfung123** [GoogleCloudPlatform/container-engine-samples#21]
I tried to optimize the resource needed. The sidecar-container pattern creates quite a lot of redundant cloudsql-proxy pods. I came cross the idea of trying to run the cloudsql-proxy in a service described in [the other issue](https://github.com/GoogleCloudPlatform/container-engine-samples/issues/8).

I wonder if we can run cloudsql proxy as daemon-set. I suppose the pod can share the same socket created by the cloudsql proxy. I tried to ask in [SO](https://stackoverflow.com/questions/43340003/can-i-run-the-cloudsql-proxy-as-a-daemon-set-in-kubernetes) with the tags suggest in the previous and there is no response so I create this issue.

**Comment by jeffmendoza** [comment]
I don't see why not. Have you run into any issues?

**Comment by edwardfung123** [comment]
Thanks for the reply. Actually, I didn't try this out. In fact, I should try but I am no longer working on GKE or k8s at this moment. I came across the out of resource issue in small cluster for dev. I suppose you guys have already tried this pattern and it should works. =

**Comment by jeffmendoza** [comment]
Cool, thanks for bringing this up.
