### ISSUE TITLE
Why is the "Using Persistent Disks with WordPress and MySQL" section using v1beta1?

### ISSUE THREAD

**Issue by chrissound** [GoogleCloudPlatform/container-engine-samples#23]
I don't see how this version relates to the rest of the versions - which is my main concern here.

**Comment by ahmetb** [comment]
@chrissound Hello, are you referring to `apiVersion: extensions/v1beta1` of mysql.yaml or wordpress.yaml files?

If so, this is about the `kind: Deployment` field. The Deployment resource type in Kubernetes is currently in beta status. Therefore it has to be referred to as its API group (i.e. extensions) and its version in there (i.e. v1beta1).

**Comment by chrissound** [comment]
Yes, I'm referring to that section.

Just seems a bit odd to have a beta version for an API on the official docs. None the less, thank you for the explanation!

**Comment by ahmetb** [comment]
I recommend following up the material with documentation on https://kubernetes.io/docs/ you'll see that the `apiVersion: extensions/v1beta1` is used there too as that’s what's available.
